language: python
# List the versions of Python you'd like to test against
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
# List the versions of Django you'd like to test against
env:
  matrix:
   - DJANGO_VERSION=1.11
   - DJANGO_VERSION=2.0
   - DJANGO_VERSION=2.1
   - DJANGO_VERSION=2.2

matrix:
  exclude:
    - python: 2.7
      env: DJANGO_VERSION=2.0
    - python: 2.7
      env: DJANGO_VERSION=2.1
    - python: 2.7
      env: DJANGO_VERSION=2.2
    - python: 3.4
      env: DJANGO_VERSION=2.1
    - python: 3.4
      env: DJANGO_VERSION=2.2

install:
  - pip install -r requirements.txt
   # Install whatever version of Django that's listed above
  - pip install -q Django<=$DJANGO_VERSION
script:
  - python runtests.py
